name: Run package
description: Package packages in the monorepo
runs:
  using: composite
  steps:
    - name: Sync packages cache
      id: sync-packages-cache
      uses: actions/cache@v2
      with:
        path: |
          node_modules/@castore/**/dist
        key: ${{ hashFiles('./packages/**') }}-${{ hashFiles('./demo/**') }}
    - name: Package
      run: if [ '${{ steps.sync-packages-cache.outputs.cache-hit }}' != 'true' ]; then yarn package; fi
      shell: bash
